Write a script using pandas to read a CSV file named sales.csv and print the first 5 rows.

In [2]:
import pandas as pd

sales = pd.read_csv("sales_data.csv") #this script we used on class i hope its okay
sales.head(5)

   order_id       product    category  price  quantity        date
0      1000    Coffee Mug   Lifestyle   7.99         1  2023-12-01
1      1001  Water Bottle   Lifestyle   9.99         1  2023-12-31
2      1002      Notebook  Stationery   3.49         2  2023-12-24
3      1003      Notebook  Stationery   3.49         4  2023-12-08
4      1004    Coffee Mug   Lifestyle   7.99         3  2023-12-20

Modify the script from Question 1 to write the read DataFrame to a new CSV file named sales_copy.csv, excluding the index

In [3]:
import pandas as pd

sales = pd.read_csv("sales_data.csv")
sales.to_csv("sales_data_copy.csv", index=False)

Write a script to read an Excel file named inventory.xlsx from the sheet named stock and print the first 5 rows.

In [4]:
import pandas as pd

df_inventory = pd.read_excel("inventory.xlsx", sheet_name="stock")
df_inventory.head(5)

        Item  Quantity  Price
0     Apples        50    0.5
1    Bananas       100    0.3
2   Cherries        75    1.2
3      Dates        30    1.5
4  Eggplants        45    0.8

Modify the script from Question 3 to write the DataFrame to a new Excel file named inventory_copy.xlsx with the sheet name as "Inventory".

In [5]:
import pandas as pd

df_inventory = pd.read_excel("inventory.xlsx", sheet_name="stock")
df_inventory.to_excel("inventory_copy.xlsx", sheet_name="inventory", index=False)

Add error handling to the script from Question 1 to catch a FileNotFoundError when the sales.csv file does not exist, printing a user-friendly error message.

In [6]:
import pandas as pd

try:
    sales = pd.read_csv("sales_data.cs")
    sales.head(5)
except FileNotFoundError:
    print("Error: File Not Found")

Error: File Not Found

Modify the script from the previous question to read only the columns `date`, `product` and `quantity` from the `sales.csv` file.

In [7]:
import pandas as pd

try:
    sales = pd.read_csv("sales_data.csv", usecols=["date", "product", "quantity"])
    print(sales.head(5))
except FileNotFoundError:
    print("Error: File Not Found")

        product  quantity        date
0    Coffee Mug         1  2023-12-01
1  Water Bottle         1  2023-12-31
2      Notebook         2  2023-12-24
3      Notebook         4  2023-12-08
4    Coffee Mug         3  2023-12-20

Write a script to read a JSON file named customers.json and print the first 5 rows.

In [10]:
import pandas as pd

clients = pd.read_json("customers.json")
clients.head(5)

   id           name  age         city
0   1       John Doe   28     New York
1   2     Jane Smith   34  Los Angeles
2   3  Emily Johnson   45      Chicago
3   4  Michael Brown   50      Houston
4   5    Sarah Davis   22      Phoenix

Change the previous script to write the DataFrame to a new JSON file named customers_copy.json. Make sure to save them as individual records and every record in a new line (without array notation).

In [11]:
import pandas as pd

clients = pd.read_json("customers.json")
clients.to_json("customers_copy.json", orient="records", lines=True)

Write a script that shows all the sheet names available in an Excel file named `data.xlsx.`

In [12]:
import pandas as pd

excel = pd.ExcelFile("data.xlsx")
print(excel.sheet_names)

['Sheet1', 'Sheet2']

Combine two CSVs, `sales_jan.csv` and `sales_feb.csv`, into a new CSV named `sales_janfeb.csv`

In [13]:
import pandas as pd

df_jan = pd.read_csv("sales_jan.csv")
df_feb = pd.read_csv("sales_feb.csv")
df = pd.concat([df_jan, df_feb])
df.to_csv("sales_janfeb.csv", index=False)

Write a script that reads the `sales.csv` file. After loading it filter out records where the quantity is more than 50. Print the result of the filtered data.

In [26]:
import pandas as pd

data = pd.read_csv("sales_data.csv")
data[data['quantity']>50]

    order_id         product     category  price  quantity        date
2       1002        Notebook   Stationery   3.49       200  2023-12-24
11      1011        Notebook   Stationery   3.49       369  2023-12-18
29      1029    Water Bottle    Lifestyle   9.99       599  2023-12-10
36      1036  Wireless Mouse  Electronics  25.99       377  2023-12-13

Read the first three chunks from a file `big_file.csv`

In [31]:
chunk_size = 1000
chunk_count = 1

for chunk in pd.read_csv("big_file.csv", chunksize=chunk_size):
    print(f"Processing chunk {chunk_count}")
    chunk_count+=1
    if chunk_count>3:
        break

Processing chunk 1
Processing chunk 2
Processing chunk 3